/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author omararias
 */
public class FrameRepararControl extends javax.swing.JFrame {

    /**
     * Creates new form FrameRepararControl
     */
    public FrameRepararControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        botonJoystick = new javax.swing.JButton();
        botonBumper = new javax.swing.JButton();
        botonGomasConductoras = new javax.swing.JButton();
        botonCruceta = new javax.swing.JButton();
        botonOtra = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setText("Registrar reparacion de control");

        botonJoystick.setText("Joystick");
        botonJoystick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJoystickActionPerformed(evt);
            }
        });

        botonBumper.setText("Bumper");
        botonBumper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBumperActionPerformed(evt);
            }
        });

        botonGomasConductoras.setText("Botones (gomas conductoras)");
        botonGomasConductoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGomasConductorasActionPerformed(evt);
            }
        });

        botonCruceta.setText("Cruceta");
        botonCruceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrucetaActionPerformed(evt);
            }
        });

        botonOtra.setText("Otra");
        botonOtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOtraActionPerformed(evt);
            }
        });

        botonAtras.setText("Atrás");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(labelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(botonAtras)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonBumper)
                            .addComponent(botonJoystick)
                            .addComponent(botonGomasConductoras)
                            .addComponent(botonCruceta)
                            .addComponent(botonOtra))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonJoystick)
                .addGap(18, 18, 18)
                .addComponent(botonBumper)
                .addGap(18, 18, 18)
                .addComponent(botonGomasConductoras)
                .addGap(31, 31, 31)
                .addComponent(botonCruceta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonOtra)
                    .addComponent(botonAtras))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonJoystickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJoystickActionPerformed
        // TODO add your handling code here:
        FrameReparacionJoystick newfrm= new FrameReparacionJoystick();
        newfrm.setVisible(true);
    }//GEN-LAST:event_botonJoystickActionPerformed

    private void botonBumperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBumperActionPerformed
        // TODO add your handling code here:
        FrameReparacionBumper newfrm=new FrameReparacionBumper();
        newfrm.setVisible(true);
    }//GEN-LAST:event_botonBumperActionPerformed

    private void botonGomasConductorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGomasConductorasActionPerformed
        // TODO add your handling code here:
        FrameReparacionGomas newfrm=new FrameReparacionGomas();
        newfrm.setVisible(true);
    }//GEN-LAST:event_botonGomasConductorasActionPerformed

    private void botonCrucetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrucetaActionPerformed
        // TODO add your handling code here:
        FrameReparacionCruceta newfrm= new FrameReparacionCruceta();
        newfrm.setVisible(true);
    }//GEN-LAST:event_botonCrucetaActionPerformed

    private void botonOtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOtraActionPerformed
        // TODO add your handling code here:
        FrameReparacionOtra newfrm= new FrameReparacionOtra();
        newfrm.setVisible(true);
       
    }//GEN-LAST:event_botonOtraActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRepararControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRepararControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRepararControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRepararControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRepararControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonBumper;
    private javax.swing.JButton botonCruceta;
    private javax.swing.JButton botonGomasConductoras;
    private javax.swing.JButton botonJoystick;
    private javax.swing.JButton botonOtra;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
