/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author omararias
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        Main.Main.verificarOCrearArchivo("registros.txt");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonRegistrarReparacion = new javax.swing.JButton();
        botonRegistrarSalida = new javax.swing.JButton();
        botonConsultarRegistros = new javax.swing.JButton();
        botonRestock = new javax.swing.JButton();
        botonInventarioPiezas = new javax.swing.JButton();
        botonPendientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SISTEMA REPARACIONES AA");

        botonRegistrarReparacion.setText("Registrar reparacion");
        botonRegistrarReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarReparacionActionPerformed(evt);
            }
        });

        botonRegistrarSalida.setText("Registrar salida");
        botonRegistrarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarSalidaActionPerformed(evt);
            }
        });

        botonConsultarRegistros.setText("Consultar registros");
        botonConsultarRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarRegistrosActionPerformed(evt);
            }
        });

        botonRestock.setText("Resurtir stock de piezas");
        botonRestock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestockActionPerformed(evt);
            }
        });

        botonInventarioPiezas.setText("Revisar inventario de piezas");
        botonInventarioPiezas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInventarioPiezasActionPerformed(evt);
            }
        });

        botonPendientes.setText("Reparaciones pendientes");
        botonPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPendientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonInventarioPiezas)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonRegistrarReparacion)
                                .addGap(29, 29, 29)
                                .addComponent(botonRegistrarSalida)
                                .addGap(34, 34, 34)
                                .addComponent(botonRestock))
                            .addComponent(botonPendientes))))
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonConsultarRegistros)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegistrarReparacion)
                    .addComponent(botonRegistrarSalida)
                    .addComponent(botonRestock))
                .addGap(44, 44, 44)
                .addComponent(botonPendientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonConsultarRegistros)
                    .addComponent(botonInventarioPiezas))
                .addGap(136, 136, 136))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarReparacionActionPerformed
        // TODO add your handling code here:
        FrameRegistrarReparacion newfrm= new FrameRegistrarReparacion();
        newfrm.setVisible(true);
    }//GEN-LAST:event_botonRegistrarReparacionActionPerformed

    private void botonRegistrarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarSalidaActionPerformed
        // TODO add your handling code here:
        FrameRegistrarSalida newfrm= new FrameRegistrarSalida();
        newfrm.setVisible(true);
    }//GEN-LAST:event_botonRegistrarSalidaActionPerformed

    private void botonRestockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestockActionPerformed
        // TODO add your handling code here:
        FrameRestock newfrm= new FrameRestock();
        newfrm.setVisible(true);
    }//GEN-LAST:event_botonRestockActionPerformed

    private void botonConsultarRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarRegistrosActionPerformed
        // TODO add your handling code here:
        FrameConsultarRegistros newfrm= new FrameConsultarRegistros();
        newfrm.setVisible(true);
    }//GEN-LAST:event_botonConsultarRegistrosActionPerformed

    private void botonInventarioPiezasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInventarioPiezasActionPerformed
        // TODO add your handling code here:
        FrameInventario newfrm= new FrameInventario();
        newfrm.setVisible(true);
    }//GEN-LAST:event_botonInventarioPiezasActionPerformed

    private void botonPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPendientesActionPerformed
        // TODO add your handling code here:
        FrameReparacionesPendientes newfrm= new FrameReparacionesPendientes();
        newfrm.setVisible(true);
    }//GEN-LAST:event_botonPendientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultarRegistros;
    private javax.swing.JButton botonInventarioPiezas;
    private javax.swing.JButton botonPendientes;
    private javax.swing.JButton botonRegistrarReparacion;
    private javax.swing.JButton botonRegistrarSalida;
    private javax.swing.JButton botonRestock;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
